const filterDataSelected = {
  searchInTitle: null,
  searchWithImages: null,
  town: null,
  district: null,
  deal: null,
  object: null,
  seller: null,
  tarif: null,
  app: {
    price: null,
    rent: null,
    rentType: null,
    type: null,
    view: null,
    floor: null,
    floorAll: null,
    floorNot: null,
    roomsCount: null,
    area: null,
    areaKitchen: null,
    areaLiving: null,
    onlineShow: null,
  },
  house: {
    roomsCount: null,
    type: null,
    view: null,
    isIntoCity: null,
    distance: null,
    areaHouse: null,
    areaLand: null,
    floorAll: null,
    price: null,
    rent: null,
    rentType: null,
    wall: null,
  },
  room: {
    price: null,
    rent: null,
    rentType: null,
    area: null,
    roomsCount: null,
    floor: null,
    floorAll: null,
    floorNot: null,
  },
  garage: {
    type: null,
    security: null,
    garageType: null,
    parkingType: null,
    area: null,
    rent: null,
    price: null,
  },
  sector: {
    price: null,
    rent: null,
    distance: null,
    area: null,
    category: null,
  },
  commercial: {
    price: null,
    rent: null,
    rentType: null,
    class: null,
    view: null,
    area: null,
    distance: null,
  },
};

export default filterDataSelected;